### ISSUE TITLE
Can't start ATS SP

### ISSUE THREAD

**Issue by Bluscream** [TheUnknownNO/TruckersMP-Launcher#5]
![s](http://image.prntscr.com/image/740cec10da8641868373a950c2214181.png)

**Comment by thomasakarlsen** [comment]
Try to run the launcher as administrator, you should also verify the games chache.

**Comment by Bluscream** [comment]
Will try.

**Comment by Bluscream** [comment]
Starting as admin and verifying the files does not change anything.

**Comment by Bluscream** [comment]
![untitled](https://cloud.githubusercontent.com/assets/3318223/15834074/e5002224-2c29-11e6-8a70-dca9078a0fc8.png)

**Comment by thomasakarlsen** [comment]
Does this issue happen if you are not using the launcher?

**Comment by Bluscream** [comment]
No. I have no problem running it through the EXE or Steam

**Comment by thomasakarlsen** [comment]
Issue should have been fixed in the Alpha 15+ releases of the launcher
