### ISSUE TITLE
Can't find/open registry key

### ISSUE THREAD

**Issue by Bluscream** [TheUnknownNO/TruckersMP-Launcher#9]
Somehow it always returns null
![image](https://cloud.githubusercontent.com/assets/3318223/21767233/190930da-d673-11e6-8004-e4e851925ecf.png)
even though the key clearly exists
![image](https://cloud.githubusercontent.com/assets/3318223/21767254/40a5e53e-d673-11e6-9742-d366f6f337f2.png)

**Comment by thomasakarlsen** [comment]
Your breakpoint is set before the code to grab the key is executed, if you move the breakpoint to the if, then you will see what the readKey value is set to. If the key was empty then the launcher would tell you that your install of truckersMP is missing or invalid and ask you to reinstall using their installer.

If this is refrencing issue #7 then this is not related at all, as it wouldnt crash the client, and even if it did, it would trigger when you first started it, and not when you click the settings button.

Remember that breakpoints happen before the selected code is run ;)

**Comment by Bluscream** [comment]
![image](https://cloud.githubusercontent.com/assets/3318223/21767806/6524d156-d676-11e6-9694-7693ef43a01c.png)
![image](https://cloud.githubusercontent.com/assets/3318223/21767652/a24ee518-d675-11e6-87e3-e3151bf72cc3.png)
Still null, and no it's not related to #7
Does it need to have some kind of elevation to read the registry key?

It would be nice to meet you on the TruckersMP TeamSpeak :)

**Comment by Bluscream** [comment]
Okay so the solution was to compile the project in 64 bit
http://stackoverflow.com/questions/2464358/why-is-opensubkey-returning-null-on-my-windows-7-64-bit-system
